### PR TITLE
updates resource output to correctly nest attributes

### PR DESCRIPTION
**Pull request by ninjapenguin**
Spec: 

> "attributes": an "attributes object", providing information about a resource.

See: http://jsonapi.org/format/#document-structure-resource-objects

### CODE REVIEW

**Comment by pmccarren** [comment]
@ninjapenguin Has json-api/json-api#588 been released yet? My understanding is that master is headed towards rc4, however it's not quite there yet (I could for sure be wrong though :) )
ref: manyminds/api2go#118

**Comment by mjanda** [comment]
Current ember-data (1.13.4) expects this format, so it should be at least optional and mentioned in readme?

**Comment by egeriis** [comment]
@ninjapenguin Can you create a new pull request which doesn't conflict with `master`? :) Thanks.

**Comment by egeriis** [comment]
Now that JSON API v1 has officially been released, it would be great to have this PR merged. @ninjapenguin do you have the time to fix the merge conflict, please?

**Comment by egeriis** [comment]
@ninjapenguin Desperately pinging you again :)

**Comment by ninjapenguin** [comment]
@egeriis I'll take a look at this and update the PR this weekend!

**Comment by egeriis** [comment]
That's just awesome @ninjapenguin :+1:

**Comment by ninjapenguin** [comment]
@egeriis This now looks fine to me!

**Comment by egeriis** [comment]
Thank you so much @ninjapenguin

**Pull request merged**
