### PR TITLE
Laravel 5 and jsonapi 1.0.0.rc2 specs

### PR DESCRIPTION
**Pull request by jpchip**
For my own project's needs, I updated your library to work with Laravel 5, updated to the jsonapi 1.0.0.rc2 specs, and added some basic support for sorting, filtering, and pagination. I wanted to offer my changes as a pull request. I have continued semantic versioning, so you can maintain Laravel 4 support in version 1.X.X. 

If you are not interested, no problem. I think I'm going to branch this off into into it's own repo and continue adding features and updating with the spec as it approaches 1.0. I wanted to thank you for providing a great base to build on, and I will continue to give you attribution in the code and in the readme.md.

### CODE REVIEW

**Comment by egeriis** [comment]
Hi Jared,

Thank you so much for this contribution. I will look into the changes you've made and give you my comments if I have any.

**Comment by egeriis** [comment]
General comment: The syntax is not compliant with PSR-2. You can easily fix this by running your contributions through `php-cs-fixer`.

**Comment by jpchip** [comment]
Thanks for the feedback!

I'm not sure I understand the "vnd" part of the MIME type. Looking at the [wikipedia](http://en.wikipedia.org/wiki/Internet_media_type#Naming) article, and other examples (eg. [github](https://developer.github.com/v3/media/)), it appears that we wouldn't replace it with our own vendor tree, but rather keep "vnd.api", as that represents the JSON API vendor. Does that make sense, or am I still missing something?

Looks like the `$relation` as key was just an over site on my part. I will update that.

I will also work on updating the syntax to be PSR-2 compliant.

**Comment by jpchip** [comment]
I looked into the `$relation` key, and according to the [specs](http://jsonapi.org/format/#document-structure-resource-relationships) it is correct for links to still be keyed by their relationship. See "author" in the example. It was just the top level resource that changed from listed under it's type to being under a generic "data".

**Comment by egeriis** [comment]
Thank you again Jared.

It looks like you're right about the vendor tree. I must have misread it back when I looking into this. I am happy that you looked it up.

I am a bit confused by the recent changes to the JSON API spec, but it looks like you're right regarding the `links` :+1:

**Comment by jpchip** [comment]
I ran PHP-CS-Fixer on the code. Thanks for introducing me to that tool, pretty handy.

I have to agree that the newest changes are a little confusing. I was surprised that they made so many breaking changes! Hopefully they won't mess around with things too much more before the spec becomes stable.

**Comment by egeriis** [comment]
Sure! It's really handy, I've implemented it as a pre-commit hook for my PHP projects. 

Yeah, I hope so. It's not clear what lacks before the spec hits 1.0.

I'll merge your pull request and tag it as v2.0.

**Comment by egeriis** [comment]
We're currently looking into using Laravel Middleware and Routers to handle some of the stuff that are done in the controllers. If you have any ideas, please let me know :)

**Comment by egeriis** [comment]
Also, if you want to improve even further, take a look here: https://scrutinizer-ci.com/g/echo-it/laravel-jsonapi/inspections/669b5fd9-c25a-48dc-b973-12a4ae862b9a

**Comment by jpchip** [comment]
Thanks! I will try to look into those scrutinizer issues sometime soon too. 

I noticed one other thing: I had updated the readme to reference my fork. I will remove that and submit another pull request. 

I haven't done much with middleware yet, but I am hoping to use it for authentication and permission checking in my project eventually. If I think of anything useful for this I'll let you know.

**Comment by egeriis** [comment]
Sounds good. Looking forward to seeing the optimizations.

Thanks for the contributions for now :)

**Pull request merged**
